version: "3.9"
services:
  api:
    image: donkeyhott/ectm-api:latest
    environment:
      DATASOURCE_URL: "${DATASOURCE_URL}"
      DATASOURCE_LOGIN: "${DATASOURCE_LOGIN}"
      DATASOURCE_PASSWORD: "${DATASOURCE_PASSWORD}"
      DDL_AUTO: "none"
      S3_HOST: "${S3_HOST}"
      S3_REGION: "${S3_REGION}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
    ports:
      - "8080:8080"

  auth:
    image: donkeyhott/ectm-auth:latest
    ports:
      - "8081:8081"

volumes:
  dbdata: